// tests/hubert/test_hubert_parity.cpp
//
// Numerical parity tests: compare C++ ggml HuBERT inference against
// reference outputs generated by the HuggingFace HubertModel in Python.
//
// Reference files are produced by tests/hubert/generate_reference.py and
// stored as raw f32 little-endian binaries whose memory layout matches
// ggml convention (ne[0] is the contiguous innermost dimension).
//
// Tests cover all model types: f32, f16, q8 (Q8_0), q5 (Q5_0), q4 (Q4_0).

#include <gtest/gtest.h>

#include "gpt_sovits/hubert.h"

#include "ggml.h"
#include "ggml-alloc.h"
#include "ggml-backend.h"
#include "ggml-cpu.h"

#include <cmath>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

namespace {

// ---------------------------------------------------------------------------
// Paths & model variants
// ---------------------------------------------------------------------------
static const std::string kTestDir = HUBERT_TEST_DIR;

struct ModelVariant {
    std::string name;
    std::string path;
    double      max_abs_tol;   // per-test max absolute error tolerance
    double      rmse_tol;      // per-test RMSE tolerance
};

// Tolerances are per-FullModel; per-block tolerances are tighter.
static const std::vector<ModelVariant> kModelVariants = {
    {"F32", kTestDir + "models/chinese-hubert-base-f32.gguf", 1e-2, 1e-3},
    {"F16", kTestDir + "models/chinese-hubert-base-f16.gguf", 2e-2, 2e-3},
    {"Q8",  kTestDir + "models/chinese-hubert-base-q8.gguf",  1e-1, 1e-2},
    {"Q5",  kTestDir + "models/chinese-hubert-base-q5.gguf",  2e-1, 3e-2},
    {"Q4",  kTestDir + "models/chinese-hubert-base-q4.gguf",  5e-1, 8e-2},
};

// Max nodes for the compute-graph context.
static constexpr size_t kMaxNodes = 8192;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

std::vector<float> load_f32_bin(const std::string & path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f.is_open()) {
        ADD_FAILURE() << "Failed to open: " << path;
        return {};
    }
    auto size = static_cast<size_t>(f.tellg());
    f.seekg(0);
    std::vector<float> data(size / sizeof(float));
    f.read(reinterpret_cast<char *>(data.data()), static_cast<std::streamsize>(size));
    return data;
}

struct ErrorStats {
    double max_abs;
    double rmse;
    double mean_abs;
};

ErrorStats compute_errors(const std::vector<float> & actual,
                          const std::vector<float> & expected)
{
    ErrorStats s{0.0, 0.0, 0.0};
    if (actual.size() != expected.size()) return s;
    double sum_sq = 0.0, sum_abs = 0.0;
    for (size_t i = 0; i < actual.size(); i++) {
        double e = std::abs(static_cast<double>(actual[i]) - static_cast<double>(expected[i]));
        s.max_abs = std::max(s.max_abs, e);
        sum_sq  += e * e;
        sum_abs += e;
    }
    s.rmse     = std::sqrt(sum_sq / static_cast<double>(actual.size()));
    s.mean_abs = sum_abs / static_cast<double>(actual.size());
    return s;
}

// RAII wrapper for the ggml context used to build compute graphs.
struct GraphContext {
    std::vector<uint8_t> buf;
    struct ggml_context * ctx = nullptr;

    explicit GraphContext(size_t max_nodes) {
        size_t sz = ggml_tensor_overhead() * max_nodes
                  + ggml_graph_overhead_custom(max_nodes, false);
        buf.resize(sz);
        struct ggml_init_params params = {
            /*.mem_size   =*/ sz,
            /*.mem_buffer =*/ buf.data(),
            /*.no_alloc   =*/ true,
        };
        ctx = ggml_init(params);
    }

    ~GraphContext() { if (ctx) ggml_free(ctx); }

    GraphContext(const GraphContext &) = delete;
    GraphContext & operator=(const GraphContext &) = delete;

    operator struct ggml_context *() { return ctx; }   // NOLINT
};

// Allocate a graph, set input, compute, and return the output as float vector.
std::vector<float> eval_graph(
    ggml_backend_t              backend,
    struct ggml_cgraph        * gf,
    const char                * input_name,
    const float               * input_data,
    size_t                      input_floats,
    const char                * output_name)
{
    ggml_gallocr_t alloc = ggml_gallocr_new(
        ggml_backend_get_default_buffer_type(backend));

    if (!ggml_gallocr_alloc_graph(alloc, gf)) {
        ADD_FAILURE() << "ggml_gallocr_alloc_graph failed";
        ggml_gallocr_free(alloc);
        return {};
    }

    struct ggml_tensor * inp = ggml_graph_get_tensor(gf, input_name);
    if (!inp) {
        ADD_FAILURE() << "Input tensor '" << input_name << "' not found in graph";
        ggml_gallocr_free(alloc);
        return {};
    }
    ggml_backend_tensor_set(inp, input_data, 0, input_floats * sizeof(float));

    if (ggml_backend_graph_compute(backend, gf) != GGML_STATUS_SUCCESS) {
        ADD_FAILURE() << "ggml_backend_graph_compute failed";
        ggml_gallocr_free(alloc);
        return {};
    }

    struct ggml_tensor * out = ggml_graph_get_tensor(gf, output_name);
    if (!out) {
        ADD_FAILURE() << "Output tensor '" << output_name << "' not found in graph";
        ggml_gallocr_free(alloc);
        return {};
    }

    size_t nbytes = ggml_nbytes(out);
    std::vector<float> result(nbytes / sizeof(float));
    ggml_backend_tensor_get(out, result.data(), 0, nbytes);

    ggml_gallocr_free(alloc);
    return result;
}

// Scale per-block tolerances relative to the full-model tolerance.
// Per-block tests accumulate less error, so tighten by a factor.
static double block_max_abs(double full_tol) { return full_tol * 0.5; }
static double block_rmse(double full_tol)    { return full_tol * 0.5; }

}  // anonymous namespace

// ===========================================================================
// Parameterized fixture: loads each model variant
// ===========================================================================

class HubertParity : public ::testing::TestWithParam<ModelVariant> {
protected:
    void SetUp() override {
        backend_ = ggml_backend_cpu_init();
        if (!backend_) {
            GTEST_SKIP() << "Could not init CPU backend";
        }
        const auto & v = GetParam();
        if (!gpt_sovits::hubert_model_load(v.path, model_, backend_)) {
            GTEST_SKIP() << "Could not load " << v.path;
        }
    }
    void TearDown() override {
        gpt_sovits::hubert_model_free(model_);
        if (backend_) {
            ggml_backend_free(backend_);
        }
    }

    ggml_backend_t          backend_ = nullptr;
    gpt_sovits::hubert_model model_{};
};

// ---------------------------------------------------------------------------
// Per-block parity: Feature Encoder
// ---------------------------------------------------------------------------

TEST_P(HubertParity, FeatureEncoder) {
    const auto & variant = GetParam();
    auto input = load_f32_bin(kTestDir + "ref_input.bin");
    auto ref   = load_f32_bin(kTestDir + "ref_feature_encoder.bin");
    ASSERT_FALSE(input.empty());
    ASSERT_FALSE(ref.empty());

    GraphContext gctx(kMaxNodes);
    ASSERT_NE(gctx.ctx, nullptr);

    struct ggml_cgraph * gf = ggml_new_graph_custom(gctx, kMaxNodes, false);

    struct ggml_tensor * inp = ggml_new_tensor_1d(gctx, GGML_TYPE_F32,
                                                   static_cast<int64_t>(input.size()));
    ggml_set_name(inp, "input");
    ggml_set_input(inp);

    struct ggml_tensor * out =
        gpt_sovits::hubert_feature_encoder_block_forward(
            gctx, inp, model_.weights.feature_encoder);
    ggml_set_name(out, "output");
    ggml_set_output(out);
    ggml_build_forward_expand(gf, out);

    auto result = eval_graph(model_.backend, gf,
                             "input",  input.data(),  input.size(),
                             "output");
    ASSERT_EQ(result.size(), ref.size())
        << "output size " << result.size() << " != ref size " << ref.size();

    auto err = compute_errors(result, ref);
    printf("  [%s] Feature Encoder : max_abs=%.4e  rmse=%.4e  mean_abs=%.4e\n",
           variant.name.c_str(), err.max_abs, err.rmse, err.mean_abs);

    EXPECT_LT(err.max_abs, block_max_abs(variant.max_abs_tol))
        << variant.name << " max abs error too large for feature encoder";
    EXPECT_LT(err.rmse,    block_rmse(variant.rmse_tol))
        << variant.name << " RMSE too large for feature encoder";
}

// ---------------------------------------------------------------------------
// Per-block parity: Encoder Layer 0
// ---------------------------------------------------------------------------

TEST_P(HubertParity, EncoderLayer0) {
    const auto & variant = GetParam();
    auto input = load_f32_bin(kTestDir + "ref_encoder_input.bin");
    auto ref   = load_f32_bin(kTestDir + "ref_encoder_layer0.bin");
    ASSERT_FALSE(input.empty());
    ASSERT_FALSE(ref.empty());

    const int64_t T = static_cast<int64_t>(input.size()) / 768;

    GraphContext gctx(kMaxNodes);
    ASSERT_NE(gctx.ctx, nullptr);

    struct ggml_cgraph * gf = ggml_new_graph_custom(gctx, kMaxNodes, false);

    struct ggml_tensor * inp = ggml_new_tensor_2d(gctx, GGML_TYPE_F32, 768, T);
    ggml_set_name(inp, "input");
    ggml_set_input(inp);

    struct ggml_tensor * out =
        gpt_sovits::hubert_encoder_layer_block_forward(
            gctx, inp, model_.weights.encoder.layers[0]);
    ggml_set_name(out, "output");
    ggml_set_output(out);
    ggml_build_forward_expand(gf, out);

    auto result = eval_graph(model_.backend, gf,
                             "input",  input.data(),  input.size(),
                             "output");
    ASSERT_EQ(result.size(), ref.size())
        << "output size " << result.size() << " != ref size " << ref.size();

    auto err = compute_errors(result, ref);
    printf("  [%s] Encoder L0      : max_abs=%.4e  rmse=%.4e  mean_abs=%.4e\n",
           variant.name.c_str(), err.max_abs, err.rmse, err.mean_abs);

    EXPECT_LT(err.max_abs, block_max_abs(variant.max_abs_tol))
        << variant.name << " max abs error too large for encoder layer 0";
    EXPECT_LT(err.rmse,    block_rmse(variant.rmse_tol))
        << variant.name << " RMSE too large for encoder layer 0";
}

// ---------------------------------------------------------------------------
// End-to-end parity: Full Model
// ---------------------------------------------------------------------------

TEST_P(HubertParity, FullModel) {
    const auto & variant = GetParam();
    auto input = load_f32_bin(kTestDir + "ref_input.bin");
    auto ref   = load_f32_bin(kTestDir + "ref_model_output.bin");
    ASSERT_FALSE(input.empty());
    ASSERT_FALSE(ref.empty());

    GraphContext gctx(kMaxNodes);
    ASSERT_NE(gctx.ctx, nullptr);

    struct ggml_cgraph * gf = ggml_new_graph_custom(gctx, kMaxNodes, false);

    struct ggml_tensor * inp = ggml_new_tensor_1d(gctx, GGML_TYPE_F32,
                                                   static_cast<int64_t>(input.size()));
    ggml_set_name(inp, "input");
    ggml_set_input(inp);

    struct ggml_tensor * out =
        gpt_sovits::hubert_model_block_forward(gctx, inp, model_.weights);
    ggml_set_name(out, "output");
    ggml_set_output(out);
    ggml_build_forward_expand(gf, out);

    auto result = eval_graph(model_.backend, gf,
                             "input",  input.data(),  input.size(),
                             "output");
    ASSERT_EQ(result.size(), ref.size())
        << "output size " << result.size() << " != ref size " << ref.size();

    auto err = compute_errors(result, ref);
    printf("  [%s] Full Model      : max_abs=%.4e  rmse=%.4e  mean_abs=%.4e\n",
           variant.name.c_str(), err.max_abs, err.rmse, err.mean_abs);

    EXPECT_LT(err.max_abs, variant.max_abs_tol)
        << variant.name << " max abs error too large for full model";
    EXPECT_LT(err.rmse,    variant.rmse_tol)
        << variant.name << " RMSE too large for full model";
}

INSTANTIATE_TEST_SUITE_P(
    HubertParity,
    HubertParity,
    ::testing::ValuesIn(kModelVariants),
    [](const ::testing::TestParamInfo<ModelVariant> & info) {
        return info.param.name;
    });
